<?php

namespace KrubiK\Console;
/*
| Krubot BotEngine: The Architect's Lexicon [×0.7 ALPHA×] 🚀📜
|--------------------------------------------------------------------------
| This is **a Playground For Mastery**, a laboratory of ***Software Dev Artistry***;
| not a weapon for production's final battles.
|
| Our Bond: ***"Rebuilding The Rebellion"*** Within S.N.P. (The Foundation of Pure Power & Revel).
| Your Mandate [MIT]: Deconstruct Krubot. Command it. Master it. You are The Architect Now!
|
| *Go build something revolutionary!* 💜⚡️
*/

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use KrubiK\Krubot;

class CacheNexusesCommand extends Command
{
    protected $signature = 'krubik:nexus-cache';
    protected $description = 'Discover and cache the full list of Nexus classes for maximum performance.';

    public function handle(Krubot $krubot): int
    {
        $this->info('🚀 Caching Nexus manifest...');

        $cachePath = config('krubot.cache.path');
        
        // Clear any old cache.
        if (File::exists($cachePath)) {
            File::delete($cachePath);
        }

        // We need the *full* list, so we call the boot logic manually.
        // The service provider already loaded them into the main instance.
        $nexuses = $krubot->getIntegratedNexuses();

        if (empty($nexuses)) {
            $this->warn('No Nexuses found to cache. The cache file will not be created.');
            return self::SUCCESS;
        }

        // Prepare the content for the cache file.
        $content = "<?php\n\n// This file is auto-generated by the krubot:nexus-cache command.\n// Do not edit it manually!\n\nreturn " . var_export($nexuses, true) . ";\n";

        // Ensure the cache directory exists.
        File::ensureDirectoryExists(dirname($cachePath));
        File::put($cachePath, $content);

        $this->info("✅ Nexus manifest cached successfully. (" . count($nexuses) . " total)");
        return self::SUCCESS;
    }
}
